#!/usr/bin/env bash
#
# loop over folders to stow dotfiles
DOTFILES=$HOME/.dotfiles
STOW_FOLDERS="bin,btop,cursor,fastfetch,ghostty,home,hypr,nvim,opencode,scripts,systemd,tmux,walker,waybar,zsh"

pushd $DOTFILES

if [[ $1 == clean ]]
then
    for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
    do
        echo "unlinking + removing $folder"
        stow -D $folder
    done
else
    for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
    do
        echo "symlinking $folder"
        stow -D $folder
        stow $folder --adopt
    done
fi
popd
