#!/usr/bin/env zsh
#
# installs all important programs
#
# checks if package is installed
#if (dpkg-query -W -f='${Status}' tmux 2>/dev/null | grep -c "ok installed") == 0


install () {
    sudo apt install -y $1
}

# update ubuntu first
sudo apt-get update
sudo apt-get upgrade

# install some basic stuff
install tmux
install stow
install tree
#dependecy for pylsp
install python3-venv
install python3-pip

#install oh-my-zsh https://ohmyz.sh/#install
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

#install vim-plug https://github.com/junegunn/vim-plug
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

#install nvm for node.js
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

#install stuff to install neovim
sudo apt install clang-9 --install-suggests
pip install cmake
sudo apt-get install ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl doxygen

#clone neovim repo and make
cd
git clone https://github.com/neovim/neovim
cd neovim && make
sudo make install
