-- local api = require('remote-sshfs.api')
-- vim.keymap.set('n', '<leader>rc', api.connect, {desc = "[R]emote [C]onnect"})
-- vim.keymap.set('n', '<leader>rd', api.disconnect, {desc = "[R]emote [D]isconnect"})
-- vim.keymap.set('n', '<leader>re', api.edit, {desc = "[R]emote (SSH) Config [E]dit"})
