-- SUPER+SHIFT+SPACE is a Quattro bar toggle by default; use it for workspace swapping instead.
hl.unbind("SUPER + SHIFT + SPACE")
hl.unbind("SUPER + L")
o.bind("SUPER + SHIFT + SPACE", "Swap workspaces between monitors", function()
  hl.dispatch(hl.dsp.workspace.swap_monitors({ monitor1 = "DP-1", monitor2 = "DP-2" }))
end)
o.bind("SUPER + H", "Move workspace to left monitor", function()
  hl.dispatch(hl.dsp.workspace.move({ monitor = "DP-1" }))
end)
o.bind("SUPER + L", "Move workspace to right monitor", function()
  hl.dispatch(hl.dsp.workspace.move({ monitor = "DP-2" }))
end)
