general {
    after_sleep_cmd = sleep 1 && hyprctl dispatch dpms on && powerprofilesctl set balanced  # delay for PAM readiness, then restore display and default power profile.
}

listener {
    timeout = 1800                                           # 30min
    on-timeout = brightnessctl -sd '*::kbd_backlight' set 0  # save state and turn off keyboard backlight
    on-resume = brightnessctl -rd '*::kbd_backlight'         # restore keyboard backlight
}

listener {
    timeout = 1800                                           # 30min
    on-timeout = powerprofilesctl set power-saver && hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && powerprofilesctl set balanced && brightnessctl -r
}
