-- Learn how to configure Hyprland: https://wiki.hypr.land/Configuring/Start/
dofile((os.getenv("OMARCHY_PATH") or "/usr/share/omarchy") .. "/default/hypr/bootstrap.lua")
require("default.hypr.omarchy")
require("hypr.monitors")
require("hypr.input")
require("hypr.bindings")
require("hypr.looknfeel")
require("hypr.autostart")
require("default.hypr.toggles")

o.window(".*", { opacity = "1.0 1.0" })
o.window(".*", { idle_inhibit = "fullscreen" })
o.window("md\\.obsidian\\.Obsidian", { workspace = "3 silent" })
o.window("teams-for-linux", { workspace = "4 silent" })
o.window("com\\.t3tools\\.T3Code", { workspace = "5 silent" })
