[theme]
name = "terminal"

[terminal]
default_shell = "/usr/bin/zsh"
new_cwd = "follow"

[keys]
prefix = "ctrl+space"

reload_config = "prefix+r"
resize_mode = "prefix+shift+r"

split_horizontal = "prefix+\""
split_vertical = "prefix+%"
new_tab = ""

focus_pane_left = "prefix+h"
focus_pane_down = "prefix+j"
focus_pane_up = "prefix+k"
focus_pane_right = "prefix+l"

new_workspace = "prefix+shift+s"
workspace_picker = ["prefix+shift+w", "prefix+shift+l"]
goto = "prefix+g"
navigate_workspace_up = "k"
navigate_workspace_down = "j"
settings = "prefix+comma"

close_tab = "prefix+q"
detach = "prefix+shift+q"
close_pane = "prefix+shift+x"

[[keys.command]]
key = "prefix+w"
type = "shell"
command = "$HOME/.local/bin/herdr-tab-create-next"
description = "create tab after current"

[[keys.command]]
key = "prefix+<"
type = "shell"
command = "$HOME/.local/bin/herdr-tab-move left"
description = "move tab left"

[[keys.command]]
key = "prefix+>"
type = "shell"
command = "$HOME/.local/bin/herdr-tab-move right"
description = "move tab right"

[[keys.command]]
key = "prefix+s"
type = "plugin_action"
command = "workspace-tab-history.toggle-workspace"
description = "toggle recent workspaces"

[[keys.command]]
key = "prefix+space"
type = "plugin_action"
command = "workspace-tab-history.toggle"
description = "toggle recent workspace tabs"

[[keys.command]]
key = "prefix+f"
type = "popup"
command = "herdr-sessionizer"
description = "open project workspace"
width = "80%"
height = "80%"

[ui]
accent = "#5eacd3"
prompt_new_tab_name = false

[ui.sound]
enabled = false
